In [2]:
import numpy as np

## array 创建数组

In [11]:
#array()函数，括号内可以是列表、元组、数组、迭代对象
np.array([1,2,3,4,5,6])
type(np.array([1,2,3,4,5,6]))

numpy.ndarray

In [12]:
# 元组
a = np.array((1,2,3,4,5))
print(type(a))

<class 'numpy.ndarray'>


In [13]:
# 迭代对象
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# 生成器
np.array([i ** 2 for i in range(10)])

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

### 练习：创建10以内的偶数数组

In [4]:
#numpy
np.array(range(2,11,2))

array([ 2,  4,  6,  8, 10])

In [3]:
#列表中元素不相同 改为最大的类型
np.array([1,2,3,4,"3"])

array(['1', '2', '3', '4', '3'], dtype='<U11')

In [5]:
ar1 = np.array(range(10))   # 整型
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# 浮点型
ar2 = np.array([1,2,3.14,5])
ar2

array([1.  , 2.  , 3.14, 5.  ])

In [9]:
# 二维数组  嵌套序列
ar3 = np.array([
    [1,2,3],
    ('a','b','c')
])
ar3

array([['1', '2', '3'],
       ['a', 'b', 'c']], dtype='<U11')

In [10]:
# 注意嵌套序列数列不一样会怎么样
ar4 = np.array([
    [1,2,3],
    [1,2,3,4,5]
])
ar4

<ipython-input-10-a5f030f4ae09>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  ar4 = np.array([


array([list([1, 2, 3]), list([1, 2, 3, 4, 5])], dtype=object)

### 设置dtype参数默认自动识别

In [12]:
a = np.array([1,2,3,4,5])
print(a)
# 设置数组元素类型
has_dtype_a = np.array([1,2,3,4,5],dtype="float")
has_dtype_a

[1 2 3 4 5]


array([1., 2., 3., 4., 5.])

In [13]:
# 若是将浮点型的数据转为整型的数据
a = np.array([1.1,2,3.3,4,5.5],dtype='int')
a

array([1, 2, 3, 4, 5])

In [20]:
list1 = [1,2,3,4]
list2 = list1
list2[1] = 5
print("list2:",list2)
print("list1:",list1)
#  如果以这种方式赋值，不是复制，而是相当于引用

list2: [1, 5, 3, 4]
list1: [1, 5, 3, 4]


#### 设置copy参数 默认为True

In [21]:
a = np.array([1,2,3,4,5])
# 定义b 复制a
b = np.array(a) 
b[1]=6
print("b:",b,"b的内存地址:",id(b))
print("a:",a,"a的内存地址:",id(a))

b: [1 6 3 4 5] b的内存地址: 2563404962592
a: [1 2 3 4 5] a的内存地址: 2563403934336


In [29]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [31]:
np.arange(20,step=2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

#### 题目：
在庆祝活动中，在200m的校园干道一侧，
从起点开始，每隔3m插一面彩旗，由近到远排成一排问：

1.最后一面彩旗能插到终点吗？

2.一共应插多少面彩旗

In [33]:
print(200 in(np.arange(0,201,3)))
print(len(np.arange(0,201,3)))

False
67


### linespace()创建等差序列
**np.linespace(start,stop,num,endpoint,retstep,dtype)**

start: 必填 序列的启示项

stop: 必填 序列的终止项

num:  要生成的等步长的样本数量，默认是50

endpoint: 该值为true时,数列中包含stop值，反之不包含，默认为true

retstep: 如果为True时，生成数组中会显示间距，反之不显示

dtype: nparray的数据类型


In [38]:
np.linspace(0,9,4)

array([0., 3., 6., 9.])

In [39]:
# 设置参数endpoint，为false时，不包含终止值
np.linspace(0,10,num=5,endpoint=False)

array([0., 2., 4., 6., 8.])

In [42]:
# 设置参数retstep，为True时，显示计算后的步长
np.linspace(0,10,num=5,endpoint=False,retstep=True)

(array([0., 2., 4., 6., 8.]), 2.0)

### 等差数列 在线性回归经常作为样本集

例如在[0,100]之间500个等差数列数据集合作为样本特征，根据目标线性方程y=3x+2，生成相应的标签集合y_data


In [ ]:
x_data = np.linspace(0,100,500)
print(x_data)
y_data = 3*x_data+2
y_data

### 等比数列

返回在间隔[开始,停止]上计算的num个均匀间隔的样本，**数组是一个等比数列构成**

np.logspace(start,stop,num=50,endpoint=True,base=10,dtype=None)
start: 必填项 起始值

stop: 必填项 终止值 如果endpoint为True 该值包含于数列中

num: 生成样本数量 默认为50

endpoint: 该值为True时，包含stop值 默认为True

base: 对数log的底数

dtype:ndarray的数据类型